source 'https://github.com/CocoaPods/Specs.git'

target 'PusherSwift', :exclusive => true do
  pod "PusherSwift", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PusherSwift", :path => "../"

  
end
