source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'PusherSwift', :exclusive => true do
  pod "PusherSwift", :path => "../"
  pod 'Alamofire', '~> 1.1'
  pod 'Starscream', :git => "https://github.com/daltoniam/starscream.git", :tag => "0.9.1"
  pod 'SwiftyJSON', '2.1.3'
end

target 'Tests', :exclusive => true do
  pod "PusherSwift", :path => "../"

  
end
